exec-once = foot --server
exec-once = systemctl --user start hyprpolkitagent
exec-once = coolercontrol --hide
exec-once = naiveproxy ~/.config/naive-proxy/config.json --hide

monitor=DP-2,2560x1080@120,0x0,1

$terminal = footclient
$fileManager = thunar
$menu = fuzzel

general {
    gaps_in = 1
    gaps_out = 1
    border_size = 1
    col.active_border = rgba(595959aa)
    col.inactive_border = rgba(11111111)
}

decoration {
    rounding = 0
    }

animations {
    enabled = no
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

input {
    kb_layout = us,ru
    kb_options = grp:caps_toggle,ctrl:nocaps
    follow_mouse = 1
    sensitivity = 0
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

$mainMod = SUPER
source = ~/.config/hypr/binds.conf

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}



